services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: machado-comprovante-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_CACHE_TTL_SECONDS: ${REDIS_CACHE_TTL_SECONDS}
      RECEIPT_BATCH_MAX_FILES: ${RECEIPT_BATCH_MAX_FILES}
      RECEIPT_MAX_FILE_SIZE_MB: ${RECEIPT_MAX_FILE_SIZE_MB}
      RECEIPT_BATCH_MAX_SIZE_MB: ${RECEIPT_BATCH_MAX_SIZE_MB}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:17.2
    container_name: machado-comprovante-api_prod_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:8.6.1
    container_name: machado-comprovante-api_prod_redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  postgres_prod_data: