"""receipt

Revision ID: 2c7b8da3a0dc
Revises: 2b42a07fd224
Create Date: 2026-09-14 15:09:11.463467

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2c7b8da3a0dc"
down_revision: Union[str, Sequence[str], None] = "2b42a07fd224"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
                                  DO $$ BEGIN
                                      CREATE TYPE processingstatusenum AS ENUM ('FAILED', 'RECEIVED', 'PROCESSED', 'PROCESSING');
                                  EXCEPTION
                                      WHEN duplicate_object THEN null;
                                  END $$;
                              """)
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "receipts",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column("file_type", sa.String(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "processing_status",
            postgresql.ENUM(
                "FAILED",
                "RECEIVED",
                "PROCESSED",
                "PROCESSING",
                name="processingstatusenum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "extracted_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "file_hash", name="uq_receipts_user_id_file_hash"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("receipts")
    op.execute("DROP TYPE IF EXISTS processingstatusenum")
    # ### end Alembic commands ###
