"""add category

Revision ID: 6ca8381f3241
Revises: f4454359c470
Create Date: 2026-10-02 15:59:09.052602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ca8381f3241'
down_revision: Union[str, Sequence[str], None] = 'f4454359c470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_code', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name_code', name='uq_categories_user_id_name_code')
    )
    op.add_column('payments', sa.Column('category_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(
        "fk_payments_category_id_categories",
        "payments",
        "categories",
        ["category_id"],
        ["id"],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_payments_category_id_categories",
        "payments",
        type_="foreignkey",
    )

    op.drop_column("payments", "category_id")

    op.drop_table("categories")
    # ### end Alembic commands ###
